"use client"

import { useEffect, useState } from "react"
import { ShieldAlert, AlertCircle, Loader2, RefreshCw } from "lucide-react"
import { API_BASE, getAuthHeaders } from "@/lib/api"

interface RiskAlert {
    id: string
    name: string
    risk_probability: number
    reason: string
}

export default function StudentsPage() {
    const [alerts, setAlerts] = useState<RiskAlert[]>([])
    const [loading, setLoading] = useState(true)

    const fetchAlerts = async () => {
        setLoading(true)
        try {
            const res = await fetch(`${API_BASE}/api/at_risk_students`, {
                headers: getAuthHeaders()
            })
            if (res.ok) {
                setAlerts(await res.json())
            }
        } catch (e) {
            console.error(e)
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        fetchAlerts()
    }, [])

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
                        <ShieldAlert className="text-red-500 w-7 h-7" /> At-Risk Students
                    </h1>
                    <p className="text-slate-500 mt-1">Generated by local Random Forest & SMOTE model</p>
                </div>
                <button
                    onClick={fetchAlerts}
                    className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition shadow-sm"
                >
                    <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin text-blue-600" : ""}`} />
                    Refresh
                </button>
            </div>

            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                {loading ? (
                    <div className="h-64 flex flex-col items-center justify-center text-slate-500">
                        <Loader2 className="w-8 h-8 animate-spin text-blue-600 mb-4" />
                        <p>Running inferences through model...</p>
                    </div>
                ) : (
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-slate-50 border-b border-slate-100">
                                <th className="py-4 px-6 font-semibold text-slate-600 text-sm tracking-wide">Student ID</th>
                                <th className="py-4 px-6 font-semibold text-slate-600 text-sm tracking-wide">Name</th>
                                <th className="py-4 px-6 font-semibold text-slate-600 text-sm tracking-wide">Risk Probability</th>
                                <th className="py-4 px-6 font-semibold text-slate-600 text-sm tracking-wide">Top Contributing Factors</th>
                                <th className="py-4 px-6 font-semibold text-slate-600 text-sm tracking-wide text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {alerts.length === 0 ? (
                                <tr>
                                    <td colSpan={5} className="py-12 text-center text-slate-500">
                                        <div className="flex flex-col items-center justify-center gap-2">
                                            <AlertCircle className="w-8 h-8 text-slate-300" />
                                            No students are currently flagged as high risk.
                                        </div>
                                    </td>
                                </tr>
                            ) : (
                                alerts.map((alert, i) => (
                                    <tr key={alert.id} className="border-b border-slate-50 hover:bg-slate-50/50 transition">
                                        <td className="py-4 px-6 text-sm font-medium text-slate-900">{alert.id}</td>
                                        <td className="py-4 px-6 text-sm text-slate-600">{alert.name}</td>
                                        <td className="py-4 px-6">
                                            <div className="flex items-center gap-3">
                                                <div className="w-full bg-slate-100 rounded-full h-2.5 max-w-[100px]">
                                                    <div
                                                        className={`h-2.5 rounded-full ${alert.risk_probability > 0.8 ? 'bg-red-500' : 'bg-orange-500'}`}
                                                        style={{ width: `${alert.risk_probability * 100}%` }}
                                                    ></div>
                                                </div>
                                                <span className="text-sm font-bold text-slate-700">{(alert.risk_probability * 100).toFixed(0)}%</span>
                                            </div>
                                        </td>
                                        <td className="py-4 px-6 text-sm text-slate-500 italic">
                                            {alert.reason}
                                        </td>
                                        <td className="py-4 px-6 text-right">
                                            <button className="text-blue-600 hover:text-blue-800 text-sm font-medium transition px-3 py-1.5 rounded bg-blue-50/50 hover:bg-blue-100">
                                                View SHAP details
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    )
}
